name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app"
      - name: Resolve SPM
        run: xcodebuild -resolvePackageDependencies -scheme "App"
      - name: Build
        run: xcodebuild -scheme "App" -destination 'platform=iOS Simulator,name=iPhone 15'
      - name: Test
        run: xcodebuild test -scheme "App" -destination 'platform=iOS Simulator,name=iPhone 15'
